### PR TITLE
Rerender (next attempt)

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@djhoese Since #11 was merged, is your issue #8 solved.

**Comment by djhoese** [comment]
@kmuehlbauer I think my main issue was the type of compiler I was using/configuring. I was able to successfully build a package before. I'd have to rebuild the package now which I don't need right now. I'll close that issue and create a new one if/when I need to build vispy in a custom environment again.

**Comment by kmuehlbauer** [comment]
@djhoese Thanks for the heads-up.

**Pull request closed without merging**
