### PR TITLE
Bump to 0.6.2

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@djhoese `setuptools` should probably be added upstream as required: https://github.com/vispy/vispy/blob/2c3ab163b7e90eddb14c2cd98e91dec615acae57/setup.py#L212

The reason why you never get any error is probably that `setuptools` is always almost installed.

**Comment by hadim** [comment]
Tests pass but are not run because no backend is detected. Even with pyqt 5.13 intstalled:

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/vispy-0.6.2-py37hf5ce8a7_0.tar.bz2
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/vispy_1573836264754/work  to  /home/conda/feedstock_root/build_artifacts/vispy_1573836264754/work_moved_vispy-0.6.2-py37hf5ce8a7_0_linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/vispy_1573836264754/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                 defaults   
    bzip2:            1.0.8-h516909a_1         conda-forge
    ca-certificates:  2019.9.11-hecc5488_0     conda-forge
    certifi:          2019.9.11-py37_0         conda-forge
    dbus:             1.13.6-he372182_0        conda-forge
    expat:            2.2.5-he1b5a44_1004      conda-forge
    fontconfig:       2.13.1-h86ecdb6_1001     conda-forge
    freetype:         2.10.0-he983fc9_1        conda-forge
    freetype-py:      2.1.0.post1-py_0         conda-forge
    gettext:          0.19.8.1-hc5be6a0_1002   conda-forge
    glib:             2.58.3-py37h6f030ca_1002 conda-forge
    gst-plugins-base: 1.14.5-h0935bb2_0        conda-forge
    gstreamer:        1.14.5-h36ae1b5_0        conda-forge
    icu:              64.2-he1b5a44_1          conda-forge
    jpeg:             9c-h14c3975_1001         conda-forge
    libblas:          3.8.0-14_openblas        conda-forge
    libcblas:         3.8.0-14_openblas        conda-forge
    libclang:         9.0.0-default_hde54327_4 conda-forge
    libffi:           3.2.1-he1b5a44_1006      conda-forge
    libgcc-ng:        9.1.0-hdf63c60_0         defaults   
    libgfortran-ng:   7.3.0-hdf63c60_2         conda-forge
    libiconv:         1.15-h516909a_1005       conda-forge
    liblapack:        3.8.0-14_openblas        conda-forge
    libllvm9:         9.0.0-hc9558a2_3         conda-forge
    libopenblas:      0.3.7-h6e990d7_3         conda-forge
    libpng:           1.6.37-hed695b0_0        conda-forge
    libstdcxx-ng:     9.1.0-hdf63c60_0         defaults   
    libuuid:          2.32.1-h14c3975_1000     conda-forge
    libxcb:           1.13-h14c3975_1002       conda-forge
    libxkbcommon:     0.9.1-hebb1f50_0         conda-forge
    libxml2:          2.9.10-hee79883_0        conda-forge
    ncurses:          6.1-hf484d3e_1002        conda-forge
    nspr:             4.23-he1b5a44_0          conda-forge
    nss:              3.47-he751ad9_0          conda-forge
    numpy:            1.17.3-py37h95a1406_0    conda-forge
    openssl:          1.1.1d-h516909a_0        conda-forge
    pcre:             8.43-he1b5a44_0          conda-forge
    pthread-stubs:    0.4-h14c3975_1001        conda-forge
    pyqt:             5.12.3-py37hcca6a23_1    conda-forge
    python:           3.7.3-h33d41f4_1         conda-forge
    qt:               5.12.5-hd8c4c69_1        conda-forge
    readline:         8.0-hf8c457e_0           conda-forge
    setuptools:       41.6.0-py37_1            conda-forge
    sqlite:           3.30.1-hcee41ef_0        conda-forge
    tk:               8.6.9-hed695b0_1003      conda-forge
    vispy:            0.6.2-py37hf5ce8a7_0     local      
    xorg-libxau:      1.0.9-h14c3975_0         conda-forge
    xorg-libxdmcp:    1.1.3-h516909a_0         conda-forge
    xz:               5.2.4-h14c3975_1001      conda-forge
    zlib:             1.2.11-h516909a_1006     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/vispy_1573836264754/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/vispy_1573836264754/test_tmp
import: 'vispy'
import: 'vispy'
+ python -c 'import vispy; print(vispy.sys_info()); vispy.test()'
WARNING: Could not load OpenGL library.
Platform: Linux-4.15.0-1061-azure-x86_64-with-centos-6.10-Final
Python:   3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
NumPy:    1.17.3
App info-gathering error:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.7/site-packages/vispy/util/config.py", line 422, in sys_info
    app = use_app(call_reuse=False)  # suppress messages
  File "$PREFIX/lib/python3.7/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "$PREFIX/lib/python3.7/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "$PREFIX/lib/python3.7/site-packages/vispy/app/application.py", line 256, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'PySide2', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt

Skipping example test: Cannot test examples unless in vispy git directory
Running line endings check... 
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing succeeded (0 failed, ['pyqt4', 'pyqt5', 'pyside', 'pyside2', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', 'ipynb_webgl', '_test', 'nobackend', 'examples'] skipped) in 0.053 secondit's up to you if you want to merge or find a way to make the tests pass. s
+ exit 0

Resource usage statistics from testing vispy:
   Process count: 2
   CPU time: unavailable
   Memory: 3.1M
   Disk usage: 24B
   Time elapsed: 0:00:02.1

TEST END: /home/conda/feedstock_root/build_artifacts/linux-64/vispy-0.6.2-py37hf5ce8a7_0.tar.bz2
```

@djhoese : I will disable the tests for the moment and we can address this in another PR.

**Comment by hadim** [comment]
I have opened an issue about the tests: https://github.com/conda-forge/vispy-feedstock/issues/19

**Comment by hadim** [comment]
LGTM

**Comment by djhoese** [comment]
Hm we have setuptools listed in the pyproject.toml file: https://github.com/vispy/vispy/blob/2c3ab163b7e90eddb14c2cd98e91dec615acae57/pyproject.toml

But you're right that would make it a build dependency but not a runtime dependency which it is now. Thanks.

**Comment by djhoese** [comment]
As for the tests, from what I can tell they were disabled already anyway. Running tests on the conda-forge CIs would be very difficult as it requires installing OpenGL and make sure that a virtual display is configured for OpenGL to draw to.

**Comment by hadim** [comment]
Ok feel free to merge then.

**Comment by hadim** [comment]
@djhoese Maybe you should manually test the build just to be sure everything is fine.

**Comment by djhoese** [comment]
I'll have to wait for the package to be built on master. Redoing all of the tests from the conda-forge package is a little over kill. If I can import it and get the version then that is a pretty simple verification. The tests have been passing from the vispy upstream repository and no complaints have come from users from the PyPI sdist and wheels.

**Pull request merged**
