### PR TITLE
Update to version 0.5.1

### PR DESCRIPTION
**Pull request by davidh-ssec**

### CODE REVIEW

**Comment by davidh-ssec** [comment]
Due to a flake error this release isn't going to pass its unit tests. I'll close this and try to make a 0.5.2 (hopefully not just for the linting error) in the next hour or two.

**Comment by kmuehlbauer** [comment]
@davidh-ssec I've never seen such error on Circle like this one. Did we change anything license related (which is mentioned in the error message)? 
@ocefpaf @jakirkham Have you seen anything alike?

**Comment by ocefpaf** [comment]
@kmuehlbauer and @davidh-ssec that error means that the file listed in `license_file: LICENSE.txt` is not in the tarball.

The choices are to comment that part out and ask upstream to fix it, see if they did not renamed it to something else first, or ship that file with the recipe.

**Comment by davidh-ssec** [comment]
@ocefpaf thanks. @kmuehlbauer and I are the upstream. I'll take a look.

**Comment by kmuehlbauer** [comment]
@davidh-ssec We have LICENSE.rst, haven't we?

**Comment by ocefpaf** [comment]
> I are the upstream

Awesome :wink:

**Comment by davidh-ssec** [comment]
We have a LICENSE.txt and it was included in the last version's tarball. I'm not really sure why what I did would remove it from the source tarball. I changed the `<root>/doc` directory from being added as package data to added with `MANIFEST.in`. This shouldn't have changed the LICENSE file but I don't see it being explicitly included anywhere either.

**Comment by jakirkham** [comment]
The license file is not listed in `MANIFEST.in`. Please add `include LICENSE.txt` to `MANIFEST.in` to fix this.

**Comment by davidh-ssec** [comment]
I understand that. What I'm confused about is how the license file was present in the tarball when it was never specified anywhere.

**Comment by davidh-ssec** [comment]
Ok so checking out vispy at the v0.5.0 tag and running `python setup.py sdist` produces a tarball without the LICENSE.txt file...I have no explanation besides some semi-corrupt build environment.

**Comment by jakirkham** [comment]
No idea how the PyPI 0.5.0 sdist was produced, but it does seem to have the `LICENSE.txt` file and lists it in `SOURCES.txt`. That said, there was no `MANIFEST.in`, which should have been included automatically. So it may have been generated in a different way.

**Comment by davidh-ssec** [comment]
@jakirkham I was the one who generated the 0.5.0 release tarball and I was the one who added the `MANIFEST.in` for the 0.5.1 release (to fix another packaging issue). That's why it is confusing to me to see different package results with what should be the same build environment. Anyway, I have fixed the LICENSE file being added in the MANIFEST.in so next release should have everything needed. I'll make sure before uploading. For now I'm trying to get a few annoying bugs in before rushing this release.

**Pull request closed without merging**
