### PR TITLE
For reference purposes only: Vispy 0.6

### PR DESCRIPTION
**Pull request by hmaarrfk**
Just leaving it here, curious if you need nodejs in the build or host section.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@djhoese does 0.6 support python 2.7?

**Comment by djhoese** [comment]
Vispy 0.6 will support python 2.7. I don't see a *need* to drop it in 0.7 either, but given how long it has taken me to keep up with bugs and features we may need to drop it because of our dependencies dropping it. @larsoner and @kmuehlbauer may have other opinions.

Thanks for putting this together.

**Comment by hmaarrfk** [comment]
I was mostly asking to see if these 2.7 bugs were an issue with my recipe or with vispy itself.

I'm rather tired of working on 2.7 so I figured I would ask before ripping it out.

**Comment by djhoese** [comment]
I would guess that this is a bug in pip for 2.7 and using the `--no-cache-dir` flag.

**Comment by hmaarrfk** [comment]
Oh that is why it is a weird error message, do you know how to fix it?

**Comment by djhoese** [comment]
Not use that flag maybe? Not sure otherwise. I just noticed your use of the flag and noticed that the error message talks about `cache_dir` being a `bool` object.

**Comment by hmaarrfk** [comment]
Good catch! where is that option set.

**Comment by djhoese** [comment]
In the pip command in the `meta.yaml`

**Comment by hmaarrfk** [comment]
But that is what conda-forge [suggests](https://conda-forge.org/docs/recipe.html#optional-bld-bat-and-or-build-sh).

I can recreate the issue on my machine with:

```
conda build -m .ci_support/linux_python2.7.yaml recipe/
```

**Comment by djhoese** [comment]
@ocefpaf Any idea if other packages have run in to this python 2.7 pip bug where `--no-cache-dir` raises an exception when specified?

**Comment by hmaarrfk** [comment]
seems like it does build if you omit the `--no-cache-dir ` for python 2.7

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
