### PR TITLE
Rerendered

### LINKED ISSUE #8: Compiler error while preparing vispy 0.6
I haven't quite finished preparing vispy 0.6 for final release but am attempting to build a conda package locally for another project for the current version of vispy on github. The new version requires a cython extension to be compiled. I'm getting the following compilation error on a CentOS 7 system:

```
/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib/python3.6/site-packages/numpy/core/include -I/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/include/python3.6m -I/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib/python3.6/site-packages/numpy/core/include -c vispy/visuals/text/_sdf_cpu.c -o build/temp.linux-x86_64-3.6/vispy/visuals/text/_sdf_cpu.o
In file included from /data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from vispy/visuals/text/_sdf_cpu.c:580:
/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
gcc -pthread -shared -L/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib -Wl,-rpath=/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib,--no-as-needed -L/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib -Wl,-rpath=/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib,--no-as-needed -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -L/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 build/temp.linux-x86_64-3.6/vispy/visuals/text/_sdf_cpu.o -L/data/users/davidh/anaconda3/conda-bld/vispy_1530668391930/_build_env/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/vispy/visuals/text/_sdf_cpu.cpython-36m-x86_64-linux-gnu.so
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
gcc: error: unrecognized command line option ‘-fno-plt’
error: command 'gcc' failed with exit status 1
```

My recipe has the following sections (the rest are basically the same):

```
source:
  git_url: https://github.com/vispy/vispy.git
  git_rev: a6ec64bb7b56739b463e3c16245a31940ca4f5f7
  patches:
    - ctypes_fontconfig.diff

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - fontconfig  # [unix]
    - {{ compiler('c') }}
    - cython

  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - fontconfig  # [unix]
    - scikit-image
```

Does anyone more familiar with building conda packages have any ideas on this? Any other information needed? Is there anything that conda-forge build environments do that I should make sure I'm doing locally?

### PR DESCRIPTION
**Pull request by hmaarrfk**
@djhoese I rerendered the recipe and updated the numpy pinnings. I think this is now the "preferred way" to do it. 

Fixes #8

### CODE REVIEW

**Comment by hmaarrfk** [comment]
FYI, i'm mostly going off https://github.com/conda-forge/scikit-image-feedstock/blob/master/recipe/meta.yaml

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please lint

**Comment by hmaarrfk** [comment]
Seems like somebody else also found the linting bug. https://github.com/conda-forge/jupyterlab-feedstock/pull/127

**Comment by djhoese** [comment]
So you think that pinning for numpy will fix the compiler needed and the issues I was having in #8 ?
I suppose the CIs are happy. Have you seen anyone have progress with the linting bug? Do we need to contact some conda-forge folks to point us in the right direction?

**Comment by hmaarrfk** [comment]
Generally, I think we should follow new conda-forge pinnings. Apparently they are basically equivalent to what you had.

I'll have a look at the .6 recipe again, but it was compiling for Python 3 so thats a good sign.

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please lint

**Comment by djhoese** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@conda-forge-admin please lint

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
This kind of stuff won't work. You'll have to recreate a fresh branch. I was too naive at first and included other things in the rerendering so you'll have to just take the parts you need, line by line.

It is mostly 

```
host: 
  - numpy
run: 
  - {{ pin_compatible('numpy') }}
```
happy compiling.

**Pull request closed without merging**
